language: python

python:
    - "2.6"
    - "2.7"
    - "pypy"
    - "3.2"
    #- "pypy3" https://bitbucket.org/pypy/pypy/issue/1935/logilabcommon-0631-triggers-a-fatal
    - "3.3"
    - "3.4"

install:
    - pip install -e .
    - pip install -U -r dev_requirements.txt
script: nosetests
