language: python

python:
    - "2.6"
    - "2.7"
    - "pypy"
    - "3.2"
    - "pypy3"
    - "3.3"
    - "3.4"

install:
    - pip install -e .
    - pip install -U mock unittest2
script: nosetests
